context:
  version: "1.49.3"
  sha256: "4d7e4fdef2eca6afe07a2682151cea78781e0a4e8f9622142d9f70c083a2fd4f"

package:
  name: "help2man"
  version: ${{ version }}

source:
  url: https://ftp.gnu.org/gnu/help2man/help2man-1.49.3.tar.xz
  sha256: 4d7e4fdef2eca6afe07a2682151cea78781e0a4e8f9622142d9f70c083a2fd4f

build:
  number: 0

requirements:
  build:
   # - {{ compiler('c') }}
    - make
  host:
    - perl
  run:
    - perl

tests:
  - script:
    - help2man --help
    - test -f ${PREFIX}/bin/help2man

about:
  homepage: https://www.gnu.org/software/help2man/
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: COPYING
  summary: help2man produces simple manual pages from the --help and --version output of other commands.
  documentation: https://www.gnu.org/software/help2man/

extra:
  recipe-maintainers:
    - mariusvniekerk
