context:
  version: "3.8.2"

package:
  name: bison
  version: ${{ version }}

source:
  url: http://ftp.gnu.org/gnu/bison/bison-${{ version }}.tar.gz
  sha256: 06c9e13bdf7eb24d4ceb6b59205a4f67c2c7e7213119644430fe82fbd14a0abb

build:
  number: 0
  #detect_binary_files_with_prefix: true

requirements:
  build:
    - libtool  # [unix]
    #- {{ compiler('c') }}
    #- {{ compiler('cxx') }}
    - m4
    - perl
    - make
    - flex   # [build_platform != target_platform]
  host:
    - flex
  run:
    - flex

tests:
  - script:
    - yacc --help   # [unix]
    - bison --help  # [unix]

about:
  homepage: https://www.gnu.org/software/bison/
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: COPYING
  summary: General purpose parser generator converting annotated context-free grammar to a deterministic LR/GLR parser.
  description: |
    Bison is a general-purpose parser generator that converts an annotated
    context-free grammar into a deterministic LR or generalized LR (GLR) parser
    employing LALR(1) parser tables.
  repository: https://git.savannah.gnu.org/git/bison.git
  documentation: http://savannah.gnu.org/projects/bison/

extra:
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - ocefpaf
