context:
  version: "1.7.1"

package:
  name: jq
  version: ${{ version }}

source:
  url: https://github.com/jqlang/jq/releases/download/jq-${{ version }}/jq-${{ version }}.tar.gz
  patches:   # [linux]
    - 0001-disable-color-tests.patch  # [linux]
  sha256: 478c9ca129fd2e3443fe27314b455e211e0d8c60bc8ff7df703873deeee580c2

build:
  number: 0

requirements:
  build:
    - gnuconfig  # [unix]
   # - {{ compiler('c') }}
    - make
  host:
    - oniguruma 6.9.*
  run:
    - oniguruma 6.9.*

tests:
  - script:
    - jq --help  # [not win]

about:
  homepage: https://jqlang.github.io/jq/
  license: MIT
  license_file: COPYING
  summary: A command-line JSON processor.

extra:
  recipe-maintainers:
    - jakirkham
    - '0xbe7a'
