schema_version: 1

context:
  version: 3.31.4

package:
  name: cmake
  version: ${{ version }}

source:
  url: https://github.com/Kitware/CMake/releases/download/v${{ version }}/cmake-${{ version }}.tar.gz
  sha256: a6130bfe75f5ba5c73e672e34359f7c0a1931521957e8393a5c2922c8b0f7f25

build:
  number: 0

requirements:
 # build:
   # - ${{ stdlib('c') }}
   # - ${{ compiler('c') }}
   # - ${{ compiler('cxx') }}
   # - cmake-no-system
  #  - ninja
   # - if: win
   #   then: 7za
  #host:
  #  - bzip2
  #  - libcurl
  #  - expat
  #  - if: unix
  #    then: ncurses
  #  - liblzma-devel
  #  - zlib
  #  - libuv
  #  - if: unix
  #    then: rhash
  #  - zstd
#  ignore_run_exports:
  #  - vc

tests:
  - script:
      - cmake --version
      - ctest --version
      - cpack --version

about:
  license: BSD-3-Clause
  license_file:
    - Copyright.txt
    - if: win
      then: Utilities/cmlibrhash/COPYING
    - if: win
      then: Utilities/cmpdcurses/README.md
    - if: win
      then: Utilities/cmpdcurses/wincon/README.md
    - Utilities/cmcppdap/LICENSE
    - Utilities/cmlibarchive/COPYING
    - Utilities/cmjsoncpp/LICENSE
  summary: CMake is an extensible, open-source system that manages the build process
  homepage: http://www.cmake.org/
  repository: https://gitlab.kitware.com/cmake/cmake
  documentation: https://cmake.org/documentation

extra:
  recipe-maintainers:
    - blowekamp
    - groutr
    - jakirkham
    - jschueller
    - ocefpaf
    - msarahan
    - scopatz
    - tadeu
    - marcelotrevisani

