{% set version = "1.17" %}

package:
  name: automake
  version: {{ version }}

source:
  url: http://ftp.gnu.org/gnu/automake/automake-{{ version }}.tar.gz
  sha256: 397767d4db3018dd4440825b60c64258b636eaf6bf99ac8b0897f06c89310acd

build:
  number: 0
  skip: true  # [win]
  ignore_run_exports_from:
    - perl 5.*

requirements:
  build:
    - make
  host:
    - m4
    - autoconf
    - perl 5.*
    - make
  run:
    - m4
    - autoconf
    - perl 5.*

test:
  commands:
    - automake --help

about:
  home: http://www.gnu.org/software/automake/
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: Tool for automatically generating Makefile.in files compliant with the GNU Coding Standards.
  description: |
    Automake is a tool for automatically generating Makefile.ins from files
    called Makefile.am.  It assumes that the project uses Autoconf and enforces
    certain restrictions on the configure.ac contents.
  dev_url: https://git.savannah.gnu.org/git/automake.git
  doc_url: https://www.gnu.org/software/automake/manual/automake.html
  doc_source_url: http://git.savannah.gnu.org/cgit/automake.git/tree/doc

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - mingwandroid
