context:
  unix_version: "5.36.3"
  major_minor_version: "5.36"
package:
  name: perl
  version: ${{ unix_version }}  # [not win]

source:
  - url: http://www.cpan.org/src/5.0/perl-${{ unix_version }}.tar.xz                                                 # [unix]
    sha256: 45a228daef66d02fdccc820e71f87e40d8e3df1fc4431f8d4580ec08033866bd                                        # [unix]
    patches:                                                                                                        # [unix]
      - 0001-Use-userelocatableinc-together-with-useshrplib.patch                                                   # [unix]
      - 0002-Disable-direct-invocation-of-linker-if-LD-is-set.patch                                                 # [unix]

build:
  number: 7
 # string: {{ PKG_BUILDNUM }}_h{{ PKG_HASH }}_strawberry  # [win]
 # string: {{ PKG_BUILDNUM }}_h{{ PKG_HASH }}_perl5       # [not win]
 # run_exports:
 #   weak:
 #     - >-
 #       {{ pin_subpackage("perl", max_pin="x.x") }}
 #       *_strawberry  # [win]
 #       *_perl5       # [not win]
 #   noarch:
 #     - >-
 #       {{ pin_subpackage("perl", max_pin="x") }}
 #       *_strawberry  # [win]
 #       *_perl5       # [not win]

requirements:
  build:
  #  - {{ compiler('c') }}  # [unix]
    - make                 # [unix]
  host:
    - libxcrypt  # [linux]

tests:
  # downstreams:
  #   - git
  #   - automake
  - script:
    - perl --help
    - |  # [unix]
      perl -V:cf_by | grep -qF "'conda'"  # [unix]
      perl -V:cf_email | grep -qF "'conda'"  # [unix]
      perl -V:perladmin | grep -qF "'conda'"  # [unix]
      perl -e 'print "$_\n" for @INC' | grep -qxF "${PREFIX}/lib/perl5/site_perl"  # [unix]
      perl -e 'print "$_\n" for @INC' | grep -qxF "${PREFIX}/lib/perl5/vendor_perl"  # [unix]
      perl -e 'print "$_\n" for @INC' | grep -qxF "${PREFIX}/lib/perl5/core_perl"  # [unix]
      perl -e 'print "$_\n" for @INC' | grep -qxF "${PREFIX}/lib/perl5/${{ major_minor_version }}/site_perl"  # [unix]
      perl -e 'print "$_\n" for @INC' | grep -qxF "${PREFIX}/lib/perl5/${{ major_minor_version }}/vendor_perl"  # [unix]
      perl -e 'print "$_\n" for @INC' | grep -qxF "${PREFIX}/lib/perl5/${{ major_minor_version }}/core_perl"  # [unix]
    # conda replaces back- by forward slashes during prefix placeholder replacement on installs:
    #   This means our Config.pm and Config_heavy.pl etc. carry mixed back-/forward slashes
    #   which Perl seems to handle well, though.
    #   refs:
    #     - https://github.com/conda/conda/blob/4.10.3/conda/core/portability.py#L37-L40
    #     - https://github.com/conda/conda/pull/2630#discussion_r66468372

about:
  homepage: http://www.perl.org/
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_file:
    - Artistic  # [unix]
    - Copying   # [unix]
    - licenses/perl/Artistic  # [win]
    - licenses/perl/Copying  # [win]
  summary: "The Perl programming language interpreter."
  description: |
    Perl 5 is a highly capable, feature-rich programming language with over 29
    years of development. Perl 5 runs on over 100 platforms from portables to
    mainframes and is suitable for both rapid prototyping and large scale
    development projects.
  documentation: https://www.perl.org/docs.html
  repository: https://perl5.git.perl.org/perl.git

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - mingwandroid
    - isuruf
    - mbargull
